config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-orchid-hound.sh
        container: qc.acc_smelly-cobalt-warthog
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-olive-vulture.sh
        container: qc.doc_pretty-denim-birman
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-indigo-gharial.sh
        container: qc.doc_chummy-saffron-flounder
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-denim-civet.sh
        container: qc.doc_gamy-harlequin-robin
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-ivory-moth.sh
        container: qc.lic_cloudy-firebrick-mongoose
  QC.Met:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-olive-wolverine.sh
        container: qc.met_cranky-auburn-chin
  QC.Sec:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-black-wolf.sh
        container: qc.sec_freaky-lemon-deer
  QC.Sty:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-thistle-greyhound.sh
        container: qc.sty_muzzy-goldenrod-turtle
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-aqua-manatee.sh
        container: qc.sty_queasy-crimson-chicken
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearest-neighbor-finder get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-firebrick-hyrax.sh
        container: qc.ver_tasty-aquamarine-gharial
timeout: 5400
